dd if=/dev/urandom of=Filesystem/temp/file4M.txt bs=1M count=4
dd if=/dev/urandom of=Filesystem/temp/file8M.txt bs=1M count=8
dd if=/dev/urandom of=Filesystem/temp/file16M.txt bs=1M count=16
dd if=/dev/urandom of=Filesystem/temp/file32M.txt bs=1M count=32
dd if=/dev/urandom of=Filesystem/temp/file64M.txt bs=1M count=64
dd if=/dev/urandom of=Filesystem/temp/file128M.txt bs=1M count=128
dd if=/dev/urandom of=Filesystem/temp/file256M.txt bs=1M count=256
dd if=/dev/urandom of=Filesystem/temp/file512M.txt bs=1M count=512
dd if=/dev/urandom of=Filesystem/temp/file1G.txt bs=1G count=1
dd if=/dev/urandom of=Filesystem/temp/file2G.txt bs=1G count=2
dd if=/dev/urandom of=Filesystem/temp/file4G.txt bs=1G count=4